name: linkable_example
description: linkable example

version: 1.0.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.1.12
  linkable:
    path: ..

flutter:
  uses-material-design: true
