name: linkable_text_widget
description: A Flutter widget to add links to your text. Linkable widget is a wrapper over RichText which allows you to render links that can be clicked to redirect to the URL.
version: 4.0.0
homepage: https://github.com/rdr6000/Linkable

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.1.12

dev_dependencies:
  flutter_test:
    sdk: flutter
